// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiMYp6mh6ITGKHKQX6ebyx4h0p6tj-j5E',
    appId: '1:1068208449918:web:1e8e2d718775473ebcab2f',
    messagingSenderId: '1068208449918',
    projectId: 'parentlink-30210',
    authDomain: 'parentlink-30210.firebaseapp.com',
    storageBucket: 'parentlink-30210.appspot.com',
    measurementId: 'G-K1Y01E2M2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwXbI7GK9ttd1T770jKtHZ2YPCFERJZrU',
    appId: '1:1068208449918:android:b34ffbb5dd23f17cbcab2f',
    messagingSenderId: '1068208449918',
    projectId: 'parentlink-30210',
    storageBucket: 'parentlink-30210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvyOJiqurterFeD9rNg9Fhpt-zezHBovE',
    appId: '1:1068208449918:ios:d35628555736d48fbcab2f',
    messagingSenderId: '1068208449918',
    projectId: 'parentlink-30210',
    storageBucket: 'parentlink-30210.appspot.com',
    iosClientId: '1068208449918-aiu23279i5lgearc65tcbv4pn22rrla1.apps.googleusercontent.com',
    iosBundleId: 'com.example.parentLink',
  );
}
